# Site
site_name: Aplicação de Redes de Computadores
site_url: https://kadetete.github.io/apr-2023-2/
site_author: Guilherme Cadete

# Repository

repo_name: kadetete/apr-2023-2
repo_url: https://github.com/kadetete/apr-2023-2

# Theme
theme:
  name: material
  language: pt

nav:
- index.md
- pedra.md
- papel.md
- tesoura.md
- Ensaios:
- mermaid.md


plugins:
- mermaid2